---
title: "Home"
site: workflowr::wflow_site
output:
  workflowr::wflow_html:
    toc: false
editor_options:
  chunk_output_type: console
---

* RESULT from 2020.2.8 (add initialization; fix set seed issue)

    The result using GWASsample = 10000, REFsample = 500:

    The summary of Frobenius norm between in-sample LD and ref sample LD:
    
    | Min.  | 1st Qu. | Median | Mean | 3rd Qu. | Max. |
    |-------|---------|--------|------|---------|------|
    | 30.72 | 47.24   | 49.65  | 49.45| 52.18   | 68.92|

    The summary of max norm between in-sample LD and ref sample LD:
    
    | Min.  | 1st Qu. | Median | Mean | 3rd Qu. | Max. |
    |-------|---------|--------|------|---------|------|
    |0.1990| 0.2615  | 0.2942 |0.3065| 0.3320  | 0.7361|
    
    - lambda = 0:
        
        [default initialization](SuSiE_dsc_ukb_results_noinit_lamb0.html)
        
        [initialize with oracle](SuSiE_dsc_ukb_results_initoracle_lamb0.html)
        
        [initialize with lasso](SuSiE_dsc_ukb_results_initlasso_lamb0.html)
    
    - lambda = $10^{-4}$:
        
        [default initialization](SuSiE_dsc_ukb_results_noinit_lamb1e-4.html)
        
        [initialize with oracle](SuSiE_dsc_ukb_results_initoracle_lamb1e-4.html)
        
        [initialize with lasso](SuSiE_dsc_ukb_results_initlasso_lamb1e-4.html)
        
    - lambda = 0.1:
        
        [default initialization](SuSiE_dsc_ukb_results_noinit_lamb0.1.html)
        
        [initialize with oracle](SuSiE_dsc_ukb_results_initoracle_lamb0.1.html)
        
        [initialize with lasso](SuSiE_dsc_ukb_results_initlasso_lamb0.1.html)

    - [SuSie Initialize Problem example](SuSiE_dsc_ukb_default_2.8_susie_problem.html)
      
        [Initialize with LASSO problem](SuSiE_dsc_ukb_default_2.8_susieinitlasso_problem.html)
        
* [RESULT](SuSiE_dsc_ukb_checkLD.html) from 2020.03.15 (LD with correction for PCs VS without)

* [RESULT](SuSiE_dsc_ukb_lmvsmix.html) from 2020.04.13 (comparing results using summary statistics from simple linear model vs mixed effect model)

---------------------

* The result using GWASsample = 10000, REFsample = 500:

    - [lambda = 0](SuSiE_dsc_ukb_results_lamb0.html)
    
    - [lambda = $10^{-4}$](SuSiE_dsc_ukb_results_lamb1e-4.html)

    - [lambda = 0.1](SuSiE_dsc_ukb_results_lamb0.1.html)

* [One problem example](SuSiE_dsc_ukb_default_problem.html)
